### ISSUE TITLE
Adding subreddits to exclude does not work on chrome  49.0.2623.87

### ISSUE THREAD

**Issue by sirotnikov** [xlexi/alientube#184]
Manually adding a subreddit throws:

> options.js:864 Uncaught TypeError: Cannot set property 'disabled' of undefined(anonymous function) @ options.js:864 
which is this line:
`                this.addToExcludeButton.disabled = true;`

> This does not save and upon further reloading of the option pages I get :
> extensions::uncaught_exception_handler:8 Error in response to storage.get: TypeError: this.addSubredditExclusionItem is not a function
>     at chrome-extension://opgodjgjgojjkhlmmhdlojfehcemknnp/res/options.js:749:30
>     at Options.<anonymous> (chrome-extension://opgodjgjgojjkhlmmhdlojfehcemknnp/res/options.js:748:45)
>     at Object.callback (chrome-extension://opgodjgjgojjkhlmmhdlojfehcemknnp/res/options.js:295:29)
>     at Function.Preferences.initialise (chrome-extension://opgodjgjgojjkhlmmhdlojfehcemknnp/res/options.js:292:41)
>     at Options.<anonymous> (chrome-extension://opgodjgjgojjkhlmmhdlojfehcemknnp/res/options.js:689:39)

But the subreddit does not appear in the list, and is not filtered effectively.
